# Generated by Django 4.1.1 on 2023-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmproject', '0002_order_quantity_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=[], verbose_name='products'),
        ),
    ]
