# Generated by Django 4.1.1 on 2023-04-05 09:42

import crmproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmproject', '0003_remove_order_product_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.JSONField(default=[], verbose_name=crmproject.models.Product),
        ),
    ]
