# Generated by Django 4.1.1 on 2023-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmproject', '0006_product_description_product_rating_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('img', models.TextField(blank=True, null=True, verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='image'),
        ),
    ]
